# Generated by Django 2.1.1 on 2018-09-26 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=48)),
                ('rated', models.CharField(max_length=48)),
                ('relased', models.CharField(max_length=48)),
                ('runtime', models.CharField(max_length=48)),
                ('genre', models.CharField(max_length=48)),
                ('plot', models.CharField(max_length=250)),
                ('language', models.CharField(max_length=48)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='movies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.Movies'),
        ),
    ]
